name: storage_repository
description: Abstraction for reading and persisting data to platform specific storage.
version: 3.0.0
repository: https://github.com/salihagic/storage_repository

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
